sudo: required
services: docker
language: minimal
branches:
  only:
  - master
script:
  - DOCKER_CONTENT_TRUST=1 docker build --pull -t "bsycorp/sentry:1.0.$TRAVIS_BUILD_NUMBER" -t "bsycorp/sentry:latest" .
  - docker login -u $DOCKERUSER -p $DOCKERPASS
